### ISSUE TITLE
RightJS Slider - odd snap

### ISSUE THREAD

**Issue by sulram** [rightjs/rightjs-ui#14]
Hello Nikolay,

I think there is a problem when using Slider with snap with min and max being odd numbers.

new Slider({min: 9, max: 17, snap: 2}).insertTo('test_div').assignTo('test_input');

It always start at 10

Best regards,

Marlus Araujo

**Comment by kaievns** [comment]
Hi Marlus,

Thanks for letting me know about the issue. Just pushed a patch for the issue caa788140d04611bbc525694fe4a785b86017767 seems like it's working now

Will publish an updated build on the weekend

## 

Cheers,
Nik
