### ISSUE TITLE
Tabs style

### ISSUE THREAD

**Issue by Jafte** [rightjs/rightjs-ui#20]
Больше пожелание: вынести в опции (false/true) подгрузку стилей для табов. 
Иначе переопределять для них стили сложновато.

**Comment by kaievns** [comment]
в чем именно сложноватость выражается?

**Comment by Jafte** [comment]
Стили прописываются в хедер последней строкой и становятся приоритетными. Чтобы переопределить их приходится !important использовать в своих стилях, который сможет в дальнейших стилях перебить только !important. И вот такая куча ненужных important возникает по стилям. Хотя, может я выбрал неверный путь?

К тому же в некоторых случаях, когда внешний вид сильно отличается от стандартного, куда приятнее задавать собственный стиль для элемента с нуля, чем переопределять уже заданный.

**Comment by kaievns** [comment]
См. правила приоритетов CSS. Сначала необходимо подключать общие скрипты стили, а потом свои собственные. Т.е. если вы в хидере подключите сначала `right-tabs.js` а свои css патчи файлом ниже, то не нужно будет писать никаких `!important`. Плюс так же можно использовать более четкие CSS селекторы, они так же имеют приоритет над более простыми.

Но если вы принципиально против дефолтовых стилей, вы всегда можете открыть файл JS и удалить стили оттуда вручную (они вклеиваются в самый конец при сборке)
