### ISSUE TITLE
Small Mistake in right-Dialog.js

### ISSUE THREAD

**Issue by shaban** [rightjs/rightjs-ui#21]
Hello Niokolay,

i had a problem using right-Dialog.js in Safe-Mode.
there is a small mistake.
i found in line 580 of http://rightjs.org/builds/ui/right-dialog-src.js.

the original line and the fixed line below:

``` javascript
this.xhr = new Xhr(url, Object.merge({method:'get'}, options))
this.xhr = new RightJS.Xhr(url, Object.merge({method:'get'}, options))
```

thanx for all the awesome work btw i gladly dismiss jquery completely if i find a decent Form Validating Plugin in RightJS.

Greetings from Berlin/Germany :-)

**Comment by kaievns** [comment]
Hey Shaban, thanks for letting me know about the issue. Just pushed a fix, will publish the updated version in couple of minutes.

Regarding form validating plugin, unfortunately i didn't write one yet :) but there a whole bunch of them that are frameworks gnostic, I suppose you could use one of them

**Comment by shaban** [comment]
Thanx for the quick fix and reply.

on validation i think best i write some function, takes time but it does
the job right without trying to make me change the whole html.
sorry for offtopic, but i have seen you are now into node.js.

just my 2cents if it comes to frontend be fancy if it comes to backend
think solid and node.js is way too complicated and overestimated.
you really should take a look at golang.org.

i use nginx -> golang backend with their clean templating system -> insert
fancy stuff or nothing whatever you prefer -> rightjs

gives you amazing solidity and elegant solutions.if you have questions
about googles go language let me know.
if not simply disregard.

wish ya good times

Shaban

2012/3/30 Nikolay V. Nemshilov <
reply@reply.github.com

**Comment by kaievns** [comment]
nah, go is made by google and they will fuck it up, as per usual :)

**Comment by shaban** [comment]
lol you have a point with GWT and that kinda crap.
but this one is different its old skool stuff and it sits between the mysql
and youtube for example.
thats exactly how i use it too.

thats C Data structure (low memory consumption)
- garbage compiler
  means you can easily map relational stuff to structs with functions
  and keep them synchronous with the database.

not touching the harddisk is pure win :)
but like i say not my point molesting you, just kinda excited with this one
feels like when i started with java in the 90s :D

2012/3/31 Nikolay V. Nemshilov <
reply@reply.github.com

**Comment by kaievns** [comment]
I'm not saying it's bad, just google has it's own view on open-source, so I have my doubts that crowds will support them any close as massively as they support node.js or rails. And having a platform without proper crowd support those days is rather pointless no matter how good it is.

Besides Go is kind of like Java all over again, it might have its own reasons to exist, but it's based on yesterday's ideas and static languages are dead no matter now nicely you polish them.
