### ISSUE TITLE
billboard on video tag

### ISSUE THREAD

**Issue by selman** [rightjs/rightjs-ui#22]
Using latest right.js and billboard.js from CDN.

``` javascript
var bb = new Billboard({autostart: false});

// not working with "ended" event
"video.videos".on({
    ended: function() { bb.showNext() }
});

// working
$$('video.videos').each(function(elem, i) {
    elem.on('ended', function() { bb.showNext() })
});
```

**Comment by kaievns** [comment]
Hey,

Sorry for the delay, missed notification about this issue. I think the problem not in billboard or rightjs, but in the video tag support, the `ended` event probably doesn't bubble and therefore rightjs can't catch it up at the document level and UJS doesn't work with it.

maybe that's a but of a particular browser.
