### ISSUE TITLE
Filepath Problem in RTE. Toolbar image doesn't load.

### ISSUE THREAD

**Issue by shaban** [rightjs/rightjs-ui#23]
Hello,

the filepath on the toolbar image rte.png is hardcoded.
that causes problems when not having the image at "/images/rightjs-ui/rte.png".

Possible fixes would be.

1.) easy fix. 
Change the Documentation so people are aware of the problem and can either put it into the default location, or manually change the both occurences of that path in the javascript file right-rte.js.

2.) better fix.
add a configuration option to override the default path.

If you lemme know what you think about it i am of course game to help :)

**Comment by kaievns** [comment]
Hi,

Documentation already says that you red to download and save the image in the same location http://rightjs.org/ui/rte#usage

Some other widgets in RightJS UI use the same technique, so it's kinda conventional feature.
